### ISSUE TITLE
Incorrect impport xml.tree

### ISSUE THREAD

**Issue by PatrikRendekDDS** [ViktorStiskala/python-qrplatba#11]
Import in [https://github.com/ViktorStiskala/python-qrplatba/blob/4a73513c7c8ac01f6b32cace1bd73776326c8f83/qrplatba/svg.py#L5](https://github.com/ViktorStiskala/python-qrplatba/blob/4a73513c7c8ac01f6b32cace1bd73776326c8f83/qrplatba/svg.py#L5)
causes TypeError 

> svg_el.append(self.make_border())
TypeError: Argument 'element' has incorrect type (expected lxml.etree._Element, got xml.etree.ElementTree.Element

The import should be replaced for 
`from qrcode.compat.etree import ET`

**Comment by ViktorStiskala** [comment]
Thanks for reporting. Fixed in version `1.1.1`.
